name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        - 
          name: Login to private registry
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: ./
            file: ./Dockerfile
            platforms: linux/amd64,linux/arm64
            builder: ${{ steps.buildx.outputs.name }}
            push: true
            tags: ${{ secrets.REGISTRY_USERNAME }}/ss-hostname-fixer:${{github.ref_name}} , ${{ secrets.REGISTRY_USERNAME }}/ss-hostname-fixer:latest
